/*
BringAuto Fleet Management v2 API

Testing TenantAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_TenantAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test TenantAPIService DeleteTenant", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var tenantId int32

		httpRes, err := apiClient.TenantAPI.DeleteTenant(context.Background(), tenantId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TenantAPIService GetTenants", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.TenantAPI.GetTenants(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TenantAPIService SetTenantCookie", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var tenantId int32

		httpRes, err := apiClient.TenantAPI.SetTenantCookie(context.Background(), tenantId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
