/*
BringAuto Fleet Management v2 API

Testing CarActionAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/bringauto/fleet-management-http-client-go"
)

func Test_openapi_CarActionAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test CarActionAPIService GetCarActionStates", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var carId int32

		resp, httpRes, err := apiClient.CarActionAPI.GetCarActionStates(context.Background(), carId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CarActionAPIService PauseCar", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var carId int32

		resp, httpRes, err := apiClient.CarActionAPI.PauseCar(context.Background(), carId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CarActionAPIService UnpauseCar", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var carId int32

		resp, httpRes, err := apiClient.CarActionAPI.UnpauseCar(context.Background(), carId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
